# SPDX-License-Identifier: MIT
# CI 项目：LEDE x86_64 云编译（J1900 / J1800）
name: OWRT-ALL

# CI 计划
on:
  # 自动编译：Auto-Clean 清理完成后自动触发（每天随自动清洁跑一次；手动点 Auto-Clean 也会触发）
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  # 手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开（例如 CONFIG_PACKAGE_luci-app-openclash=y）。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

# CI 权限
permissions: write-all

# CI 任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        CONFIG: [X86]
        SOURCE: [coolsnowwolf/lede]
        BRANCH: [master]

    # 调用公用编译核心 WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      # 编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      # 默认主题（Argon）
      WRT_THEME: argon
      # 默认主机名
      WRT_NAME: openwrt
      # 默认 WIFI 名称（x86 无无线，仅占位）
      WRT_SSID: LEDE
      # 默认 WIFI 密码（x86 无无线，仅占位）
      WRT_WORD: 12345678
      # 默认登录地址
      WRT_IP: 10.0.1.1
      # 登录密码（LEDE 默认 password）
      WRT_PW: password
      # 源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      # 源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      # 源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      # 插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      # 仅输出配置文件
      WRT_TEST: ${{inputs.TEST || false}}
